import type { Quiz } from "./types";

export const quizzes: Quiz[] = [
  {
    id: "swift-basics-quiz",
    title: "Swift Basics Quiz",
    description: "20 questions on variables and constants, type inference, integers and floating point, booleans, strings, tuples, type conversion, and comments.",
    relatedArticleSlug: "swift-basics",
    questions: [
      {
        id: "q1",
        prompt: "What happens if you try to reassign a new value to a constant declared with `let`?",
        options: [
          { id: "a", text: "It compiles but Xcode shows a warning" },
          { id: "b", text: "It compiles with no issues, since `let` only applies at declaration" },
          { id: "c", text: "It's a compile-time error" },
          { id: "d", text: "It's a runtime crash" },
        ],
        correctOptionId: "c",
        explanation: "`let` constants must be assigned exactly once. Attempting a second assignment — `maxAttempts = 4` after `let maxAttempts = 3` — produces the compile-time error \"cannot assign to value: '...' is a 'let' constant.\" This is caught before the code ever runs, unlike a runtime crash.",
      },
      {
        id: "q2",
        prompt: "Which statement about deferred initialization of a `let` constant is true?",
        options: [
          { id: "a", text: "It's not allowed — `let` requires a value at the declaration line" },
          { id: "b", text: "It's allowed only inside a `class`" },
          { id: "c", text: "It's allowed as long as the compiler can prove the constant is assigned exactly once on every possible code path before its first use" },
          { id: "d", text: "It's allowed, but only if you also mark it `lazy`" },
        ],
        correctOptionId: "c",
        explanation: "Swift permits declaring a `let` without an initial value (`let temperature: Double`) and assigning it later, as long as every branch (e.g. both sides of an `if`/`else`) guarantees it's set exactly once before it's read. The compiler tracks this at compile time — no `lazy` keyword involved, and it works in functions generally, not just classes.",
      },
      {
        id: "q3",
        prompt: "What type is inferred for `let price = 19.99`?",
        options: [
          { id: "a", text: "`Float`" },
          { id: "b", text: "`Double`" },
          { id: "c", text: "`Decimal`" },
          { id: "d", text: "`Int`" },
        ],
        correctOptionId: "b",
        explanation: "Swift infers `Double` for any floating-point literal by default. To get `Float` instead, you'd need an explicit annotation: `let price: Float = 19.99`.",
      },
      {
        id: "q4",
        prompt: "Why does `var buffer: [UInt8]` require an explicit type annotation?",
        options: [
          { id: "a", text: "Arrays can never have their type inferred" },
          { id: "b", text: "`UInt8` cannot be used inside array literals" },
          { id: "c", text: "There's no initial value/literal for the compiler to infer a type from" },
          { id: "d", text: "It's a stylistic convention only, not a requirement" },
        ],
        correctOptionId: "c",
        explanation: "Type inference works by examining the literal or expression on the right-hand side of `=`. With no initial value at all, there's nothing to infer from, so an explicit annotation becomes mandatory.",
      },
      {
        id: "q5",
        prompt: "On modern Apple platforms, what is the size of the default `Int` type?",
        options: [
          { id: "a", text: "Always 32-bit, regardless of platform" },
          { id: "b", text: "Matches the platform's native word size — 64-bit on modern devices" },
          { id: "c", text: "16-bit" },
          { id: "d", text: "Arbitrary precision (grows as needed)" },
        ],
        correctOptionId: "b",
        explanation: "`Int` is platform-dependent and matches the native word size, which is 64-bit on all current Apple platforms. Fixed-width alternatives like `Int8`, `Int16`, `Int32`, `Int64` exist for when you need a guaranteed specific width.",
      },
      {
        id: "q6",
        prompt: "What happens when you compute `UInt8.max + 1` using the regular `+` operator?",
        options: [
          { id: "a", text: "It silently wraps around to `0`" },
          { id: "b", text: "It traps with a runtime \"Arithmetic overflow\" crash" },
          { id: "c", text: "It's automatically promoted to `Int` and returns `256`" },
          { id: "d", text: "It's a compile-time error" },
        ],
        correctOptionId: "b",
        explanation: "Swift integers trap on overflow by default — a deliberate safety choice, unlike C's silent wraparound. To get wraparound behavior deliberately, you must opt in explicitly with the overflow operator `&+` (`UInt8.max &+ 1` gives `0`).",
      },
      {
        id: "q7",
        prompt: "What does `7 / 2` evaluate to when both operands are `Int`?",
        options: [
          { id: "a", text: "`3.5`" },
          { id: "b", text: "`3`" },
          { id: "c", text: "`4`" },
          { id: "d", text: "A runtime crash" },
        ],
        correctOptionId: "b",
        explanation: "Integer division truncates toward zero and never auto-promotes to a floating-point result. `7 / 2` is `3`; to get `3.5` you must convert both operands to `Double` first: `Double(7) / Double(2)`.",
      },
      {
        id: "q8",
        prompt: "Why does `0.1 + 0.2 == 0.3` evaluate to `false` in Swift?",
        options: [
          { id: "a", text: "It's a bug specific to the Swift compiler" },
          { id: "b", text: "Binary floating-point representation can't exactly represent most decimal fractions" },
          { id: "c", text: "`Double` values are always compared by reference, not value" },
          { id: "d", text: "Operator precedence causes `0.2 == 0.3` to be evaluated first" },
        ],
        correctOptionId: "b",
        explanation: "This is a fundamental property of IEEE 754 binary floating-point, not a Swift-specific bug — the same result occurs in virtually every language using binary floats. `0.1 + 0.2` actually equals `0.30000000000000004`. The takeaway is to never compare floating-point values with `==`; use a tolerance-based comparison instead.",
      },
      {
        id: "q9",
        prompt: "Which type should you use for exact decimal arithmetic, such as currency calculations?",
        options: [
          { id: "a", text: "`Double`" },
          { id: "b", text: "`Float`" },
          { id: "c", text: "`Decimal`" },
          { id: "d", text: "`Int` with manual rounding" },
        ],
        correctOptionId: "c",
        explanation: "`Decimal` performs exact decimal arithmetic without the binary rounding errors inherent to `Double`/`Float`. For money specifically, `Decimal` (or integer cents) avoids surprises like `0.1 + 0.2 != 0.3`.",
      },
      {
        id: "q10",
        prompt: "Which operators in Swift are short-circuiting?",
        options: [
          { id: "a", text: "`&` and `|`" },
          { id: "b", text: "`&&` and `||`" },
          { id: "c", text: "Only `||`" },
          { id: "d", text: "Neither — Swift always evaluates both sides" },
        ],
        correctOptionId: "b",
        explanation: "`&&` and `||` stop evaluating as soon as the result is already determined by the left-hand side — e.g. `false && expensiveCheck()` never calls `expensiveCheck()`. This is also why patterns like `!array.isEmpty && array[0] == 5` are safe: the subscript is only reached if the array is confirmed non-empty first.",
      },
      {
        id: "q11",
        prompt: "What is the purpose of a `// MARK: -` comment, and does it affect compiled behavior?",
        options: [
          { id: "a", text: "It changes compiler optimization level for the following code" },
          { id: "b", text: "It's purely a navigation aid for Xcode's jump bar and has zero effect on compilation or runtime behavior" },
          { id: "c", text: "It automatically generates unit tests for the marked section" },
          { id: "d", text: "It suppresses warnings for the rest of the file" },
        ],
        correctOptionId: "b",
        explanation: "`// MARK:` comments (along with `// TODO:` and `// FIXME:`) exist purely to help Xcode organize a file's jump bar into navigable sections — the leading `-` adds a visual divider line. None of these affect compilation or runtime behavior at all; they're purely organizational, distinct from `///` documentation comments, which Xcode renders as Quick Help for a symbol.",
      },
      {
        id: "q12",
        prompt: "What is the idiomatic way to embed a variable's value inside a string?",
        options: [
          { id: "a", text: "String concatenation using `+`" },
          { id: "b", text: "String interpolation using `\\(...)`" },
          { id: "c", text: "`String(format:)` exclusively" },
          { id: "d", text: "Manual character-by-character construction" },
        ],
        correctOptionId: "b",
        explanation: "Interpolation (`\"\\(name) is \\(age) years old.\"`) is the idiomatic, readable approach in Swift, and it accepts any expression — not just simple variables, but full expressions like `\\(a + b)`.",
      },
      {
        id: "q13",
        prompt: "Why does `word[0]` fail to compile for a Swift `String`?",
        options: [
          { id: "a", text: "Strings in Swift are always immutable" },
          { id: "b", text: "Swift strings are collections of extended grapheme clusters with variable byte-width, so there's no way to jump to \"the Nth character\" in constant time — Swift refuses to hide that cost behind `Int` subscripting" },
          { id: "c", text: "It's simply a missing feature that will be added in a future release" },
          { id: "d", text: "It actually does compile and work correctly" },
        ],
        correctOptionId: "b",
        explanation: "Because characters can be composed of multiple Unicode scalars, integer indexing would silently be an O(n) operation disguised as O(1). Swift's design intentionally forces you to use `String.Index` (or convert to `[Character]`) instead of hiding that cost.",
      },
      {
        id: "q14",
        prompt: "What type do you get back when subscripting a `String` with a `Range<String.Index>`?",
        options: [
          { id: "a", text: "`String`" },
          { id: "b", text: "`Substring`" },
          { id: "c", text: "`Character`" },
          { id: "d", text: "`[Character]`" },
        ],
        correctOptionId: "b",
        explanation: "Range-subscripting a string produces a `Substring`, a lightweight view that shares storage with the original string. Convert it to a full `String` with `String(subSequence)` before storing it long-term, since a `Substring` keeps the original string's storage alive.",
      },
      {
        id: "q15",
        prompt: "In a multiline string literal (`\"\"\"...\"\"\"`), what determines how much leading whitespace is stripped from each line?",
        options: [
          { id: "a", text: "The indentation of the first line of content" },
          { id: "b", text: "The indentation of the closing `\"\"\"`" },
          { id: "c", text: "Tabs are stripped automatically; spaces never are" },
          { id: "d", text: "Nothing is stripped — all whitespace is preserved literally" },
        ],
        correctOptionId: "b",
        explanation: "The closing `\"\"\"`'s indentation level acts as the baseline; any matching leading whitespace on each content line is stripped, letting you indent a multiline string naturally within your code without that indentation leaking into the actual string value.",
      },
      {
        id: "q16",
        prompt: "What does wrapping a string in `#\"...\"#` (a raw string) do?",
        options: [
          { id: "a", text: "Enables interpolation everywhere automatically" },
          { id: "b", text: "Disables standard escape-sequence processing and interpolation, treating backslashes and quotes literally" },
          { id: "c", text: "Is purely cosmetic and behaves identically to a normal string" },
          { id: "d", text: "Converts the string to Unicode scalar view automatically" },
        ],
        correctOptionId: "b",
        explanation: "Raw strings turn off `\\n`-style escapes and `\\(...)` interpolation by default, which is why they're ideal for regex patterns or file paths full of backslashes (`#\"C:\\Users\\Nahidul\\Documents\"#`). To interpolate inside a raw string, you must match the `#` count: `#\"\\#(value)\"#`.",
      },
      {
        id: "q17",
        prompt: "What does a Swift `Character` represent?",
        options: [
          { id: "a", text: "A single raw byte" },
          { id: "b", text: "A single UTF-8 code unit" },
          { id: "c", text: "An extended grapheme cluster — a user-perceived character, which may be composed of multiple Unicode scalars" },
          { id: "d", text: "A fixed 2-byte UTF-16 code unit" },
        ],
        correctOptionId: "c",
        explanation: "Swift's `Character` type models what a human perceives as \"one character\" on screen, regardless of how many underlying Unicode scalars are combined to produce it (e.g. a letter plus a combining accent, or a flag emoji made of two regional indicator scalars).",
      },
      {
        id: "q18",
        prompt: "For the string `\"👨‍👩‍👧‍👦\"` (a family emoji made of four people joined with zero-width joiners), which statement is true?",
        options: [
          { id: "a", text: "`.count` and `.unicodeScalars.count` are equal" },
          { id: "b", text: "`.count` is `1`, while `.unicodeScalars.count` is much greater than `1`" },
          { id: "c", text: "`.count` is greater than `.utf8.count`" },
          { id: "d", text: "It's impossible to store this as a single `Character`" },
        ],
        correctOptionId: "b",
        explanation: "`.count` operates at the grapheme-cluster level, so a visually single emoji counts as `1` `Character`, even though it's built from 7 Unicode scalars joined together — and 11 UTF-16 code units, and 25 UTF-8 bytes. These different \"views\" of a string can report very different lengths.",
      },
      {
        id: "q19",
        prompt: "What is the type of `let coordinate = (2, 3)`?",
        options: [
          { id: "a", text: "`[Int]`, a two-element array" },
          { id: "b", text: "A tuple of type `(Int, Int)`" },
          { id: "c", text: "A custom `Point` struct" },
          { id: "d", text: "`Dictionary<Int, Int>`" },
        ],
        correctOptionId: "b",
        explanation: "Parentheses with comma-separated values create a tuple — a lightweight compound value with no need to declare a named type. Elements can be accessed positionally (`.0`, `.1`) or, if named (`(x: 2, y: 3)`), by name (`.x`, `.y`).",
      },
      {
        id: "q20",
        prompt: "What does `Int(\"abc\")` return?",
        options: [
          { id: "a", text: "A runtime crash" },
          { id: "b", text: "`0`" },
          { id: "c", text: "`nil`, because `Int.init?(String)` is a failable initializer" },
          { id: "d", text: "A compile-time error" },
        ],
        correctOptionId: "c",
        explanation: "Converting a `String` to a numeric type is inherently fallible — the string might not represent a valid number — so Swift's `Int(String)` initializer returns an optional (`Int?`). `Int(\"abc\")` returns `nil`, while `Int(\"42\")` returns `Optional(42)`. This is also why `// MARK:`/`///` comments matter for documenting such failable APIs clearly for other developers — the doc comment can call out that the initializer may return `nil`.",
      },
    ],
  },
  {
    id: "control-flow-quiz",
    title: "Control Flow Quiz",
    description: "20 questions on if/switch branching, every loop form, guard, break/continue, and defer.",
    relatedArticleSlug: "control-flow",
    questions: [
      {
        id: "q1",
        prompt: "What type must the condition in an `if` statement be in Swift?",
        options: [
          { id: "a", text: "Any type — Swift auto-converts to boolean" },
          { id: "b", text: "`Int`, where `0` is false and anything else is true" },
          { id: "c", text: "`Bool`, with no implicit conversion from any other type" },
          { id: "d", text: "`String`, where empty strings are false" },
        ],
        correctOptionId: "c",
        explanation: "Swift enforces that `if` conditions are genuinely `Bool` — there is no implicit truthiness conversion from `Int`, `String`, or any other type, unlike C or JavaScript.",
      },
      {
        id: "q2",
        prompt: "When using the single-expression `if` form to assign a value (`let x = if cond { a } else { b }`), what's required?",
        options: [
          { id: "a", text: "Nothing special — any mismatched branch types are automatically unified" },
          { id: "b", text: "Every branch must produce the same type" },
          { id: "c", text: "An `else` branch is optional" },
          { id: "d", text: "This syntax only works with `Bool` return values" },
        ],
        correctOptionId: "b",
        explanation: "When `if` is used as an expression to produce a value, all branches must evaluate to the same type so the compiler can determine a single result type for the whole expression, and every branch (including `else`) must be present.",
      },
      {
        id: "q3",
        prompt: "What is required for a `switch` statement over a non-enum type like `Int` to compile?",
        options: [
          { id: "a", text: "Nothing — Swift `switch` statements never require exhaustiveness" },
          { id: "b", text: "It must cover every case explicitly, one per line" },
          { id: "c", text: "It must either cover all possible values or include a `default:` case" },
          { id: "d", text: "It must always end in `break`" },
        ],
        correctOptionId: "c",
        explanation: "Swift `switch` statements must be exhaustive. For a type like `Int` with effectively infinite possible values, you satisfy exhaustiveness with a `default:` case; for enums, listing every case can satisfy exhaustiveness without `default`.",
      },
      {
        id: "q4",
        prompt: "By default, does a matched `case` in a Swift `switch` fall through into the next case?",
        options: [
          { id: "a", text: "Yes, exactly like C or Java, unless you add `break`" },
          { id: "b", text: "No — each case implicitly breaks after its body runs; `fallthrough` must be added explicitly to opt in to fall-through behavior" },
          { id: "c", text: "Only if the case doesn't include a comma-separated value list" },
          { id: "d", text: "Only for numeric switches, not for strings" },
        ],
        correctOptionId: "b",
        explanation: "Unlike C-family languages, Swift's `switch` cases do not fall through automatically — this removes a common class of forgotten-`break` bugs. If you genuinely want fall-through behavior, you opt in with the explicit `fallthrough` keyword.",
      },
      {
        id: "q5",
        prompt: "In `case 80..<90:` inside a switch over an `Int` score, which values match?",
        options: [
          { id: "a", text: "80 through 90, inclusive of both" },
          { id: "b", text: "80 up to but not including 90" },
          { id: "c", text: "Only exactly 80 or exactly 90" },
          { id: "d", text: "Any value greater than 80" },
        ],
        correctOptionId: "b",
        explanation: "`..<` is Swift's half-open range operator, excluding the upper bound. So `80..<90` matches 80 through 89. The closed range operator `...` would include 90 as well.",
      },
      {
        id: "q6",
        prompt: "In a tuple switch pattern like `case (_, 0):`, what does the underscore `_` mean?",
        options: [
          { id: "a", text: "It matches only the literal value `0`" },
          { id: "b", text: "It's a wildcard that matches any value in that position, ignoring it" },
          { id: "c", text: "It causes a compile-time error unless bound with `let`" },
          { id: "d", text: "It represents `nil`" },
        ],
        correctOptionId: "b",
        explanation: "`_` is Swift's wildcard pattern — it matches anything in that position without binding it to a name. `case (_, 0)` matches any first element, as long as the second element is exactly `0`.",
      },
      {
        id: "q7",
        prompt: "What does a `where` clause do when attached to a `switch` case, e.g. `case let (x, y) where x == y:`?",
        options: [
          { id: "a", text: "It replaces the need for a pattern entirely" },
          { id: "b", text: "It adds an additional runtime boolean condition that must also be true for the case to match, on top of the pattern itself matching" },
          { id: "c", text: "It only works with `default` cases" },
          { id: "d", text: "It forces the case to always match, ignoring the pattern" },
        ],
        correctOptionId: "b",
        explanation: "`where` lets you layer an extra condition onto a pattern match — the case only fires if the pattern matches *and* the `where` condition evaluates to `true`. This is commonly combined with value bindings, as in `case let (x, y) where x == y`.",
      },
      {
        id: "q8",
        prompt: "What does `case let (x, y):` do when matching against a tuple in a switch statement?",
        options: [
          { id: "a", text: "It's a syntax error — tuples cannot be destructured in switch cases" },
          { id: "b", text: "It binds the tuple's elements to new local constants `x` and `y` for use within that case's body" },
          { id: "c", text: "It only works if `x` and `y` were already declared elsewhere" },
          { id: "d", text: "It requires `var` instead of `let` to work at all" },
        ],
        correctOptionId: "b",
        explanation: "`case let x` (or `case var x`) is value binding — it extracts values out of the matched pattern (a tuple here, but also enum associated values or optional patterns) and binds them to new local names usable inside that case's body.",
      },
      {
        id: "q9",
        prompt: "What is the difference between `for i in 1...5` and `for i in 0..<5`?",
        options: [
          { id: "a", text: "They are identical" },
          { id: "b", text: "`1...5` includes both 1 and 5 (5 iterations: 1,2,3,4,5); `0..<5` excludes 5 (5 iterations: 0,1,2,3,4)" },
          { id: "c", text: "`0..<5` includes 5 as the final value" },
          { id: "d", text: "`1...5` only works with floating-point ranges" },
        ],
        correctOptionId: "b",
        explanation: "`...` is a closed range including both endpoints, while `..<` is half-open, excluding the upper bound. Both examples happen to iterate 5 times, but over different actual values (1–5 vs. 0–4).",
      },
      {
        id: "q10",
        prompt: "What is the key behavioral difference between `while` and `repeat-while`?",
        options: [
          { id: "a", text: "`repeat-while` is deprecated in modern Swift" },
          { id: "b", text: "`while` checks its condition before each iteration (may run zero times); `repeat-while` checks after each iteration (always runs at least once)" },
          { id: "c", text: "`while` always runs exactly once" },
          { id: "d", text: "There is no difference — they're interchangeable syntax for the same behavior" },
        ],
        correctOptionId: "b",
        explanation: "`while` evaluates its condition up front, so the loop body might never execute if the condition starts `false`. `repeat-while` (Swift's `do-while` equivalent) always executes the body at least once before checking the condition, useful for things like retry loops.",
      },
      {
        id: "q11",
        prompt: "What is the difference between `break` and `continue` inside a loop?",
        options: [
          { id: "a", text: "They are synonyms" },
          { id: "b", text: "`break` exits the loop entirely; `continue` skips the rest of the current iteration and moves to the next one" },
          { id: "c", text: "`break` skips one iteration; `continue` exits the loop entirely" },
          { id: "d", text: "`continue` can only be used inside a `switch`" },
        ],
        correctOptionId: "b",
        explanation: "`break` terminates the nearest enclosing loop (or switch case) immediately. `continue` stops the current iteration's remaining code but lets the loop proceed to its next iteration, re-evaluating the loop condition as normal.",
      },
      {
        id: "q12",
        prompt: "In nested loops, how do you make `break` or `continue` target an outer loop instead of the innermost one?",
        options: [
          { id: "a", text: "It's not possible in Swift — you'd need a boolean flag variable instead" },
          { id: "b", text: "By using a labeled statement, e.g. `outerLoop: for ... { ... break outerLoop }`" },
          { id: "c", text: "By calling `break` twice in a row" },
          { id: "d", text: "By wrapping the outer loop in a function and using `return`" },
        ],
        correctOptionId: "b",
        explanation: "A label placed before a loop (`outerLoop: for i in ...`) lets you write `break outerLoop` or `continue outerLoop` from within a nested loop, explicitly targeting that labeled loop instead of only affecting the innermost one.",
      },
      {
        id: "q13",
        prompt: "What values does `stride(from: 0, to: 20, by: 5)` produce?",
        options: [
          { id: "a", text: "0, 5, 10, 15, 20" },
          { id: "b", text: "0, 5, 10, 15 (20 excluded)" },
          { id: "c", text: "5, 10, 15, 20" },
          { id: "d", text: "An error, since `stride` requires `through:` not `to:`" },
        ],
        correctOptionId: "b",
        explanation: "`stride(from:to:by:)` is half-open, like `..<` — it excludes the final \"to\" value. To include the endpoint, use `stride(from: 0, through: 20, by: 5)`, which would produce 0, 5, 10, 15, 20.",
      },
      {
        id: "q14",
        prompt: "What is the main caution around the ternary operator (`condition ? a : b`)?",
        options: [
          { id: "a", text: "It cannot be used with `String` types" },
          { id: "b", text: "It's slower at runtime than `if`/`else`" },
          { id: "c", text: "It reads fine for one simple condition, but becomes hard to read once nested or combined with complex conditions — an `if`/`else` or `switch` is clearer at that point" },
          { id: "d", text: "It requires both branches to be the same literal value" },
        ],
        correctOptionId: "c",
        explanation: "The ternary operator is fine for compact, single-condition choices (like `age >= 18 ? \"Adult\" : \"Minor\"`), but nesting ternaries (`a > b ? (a > c ? a : c) : ...`) quickly becomes difficult to parse visually — that logic reads far more clearly as a plain `if`/`else` or a small helper function.",
      },
      {
        id: "q15",
        prompt: "What must the `else` branch of a `guard` statement do?",
        options: [
          { id: "a", text: "Nothing in particular — it's optional" },
          { id: "b", text: "It must exit the current scope, e.g. via `return`, `break`, `continue`, or `throw`" },
          { id: "c", text: "It must always call `fatalError()`" },
          { id: "d", text: "It must reassign the bound variable to a default value" },
        ],
        correctOptionId: "b",
        explanation: "`guard`'s `else` clause is mandatory and must transfer control out of the current scope. This is what guarantees that any values bound in the `guard`'s condition are safe to use for the rest of the enclosing scope — if the condition fails, control never reaches that code.",
      },
      {
        id: "q16",
        prompt: "What is the key structural advantage of `guard let x = ...` over `if let x = ...` for validating multiple inputs at the top of a function?",
        options: [
          { id: "a", text: "`guard let` runs faster at runtime" },
          { id: "b", text: "Bindings from `guard let` remain available for the rest of the enclosing scope, avoiding the deep nesting that repeated `if let` blocks would require" },
          { id: "c", text: "`guard let` can bind more variables at once than `if let`" },
          { id: "d", text: "There is no actual difference between them" },
        ],
        correctOptionId: "b",
        explanation: "With `if let`, the unwrapped binding is only visible inside that `if`'s indented block, so validating several optionals in sequence nests deeper and deeper. `guard let`'s binding escapes into the rest of the function, keeping the \"happy path\" flat and unindented.",
      },
      {
        id: "q17",
        prompt: "When does a `defer` block execute?",
        options: [
          { id: "a", text: "Immediately, at the point it's written in the code" },
          { id: "b", text: "Only if the function throws an error" },
          { id: "c", text: "When the current scope exits, whether through normal completion, an early `return`, a thrown error, or a `break`" },
          { id: "d", text: "Only once, the first time the containing function is ever called" },
        ],
        correctOptionId: "c",
        explanation: "`defer` schedules code to run whenever the enclosing scope exits, regardless of the exit path — normal fall-through completion, an early return, a thrown error, or a break out of a loop. It's Swift's mechanism for guaranteed cleanup.",
      },
      {
        id: "q18",
        prompt: "If a function contains three `defer` blocks in sequence, in what order do they execute when the function exits?",
        options: [
          { id: "a", text: "In the same order they were written (first-in-first-out)" },
          { id: "b", text: "In reverse order — the last `defer` written runs first (last-in-first-out)" },
          { id: "c", text: "In random order" },
          { id: "d", text: "Only the last `defer` block actually runs; the others are ignored" },
        ],
        correctOptionId: "b",
        explanation: "Multiple `defer` blocks in the same scope execute in reverse order, like a stack (LIFO). This matters for symmetric setup/teardown — e.g., releasing a lock before closing the resource it was protecting, in the exact reverse order they were acquired.",
      },
      {
        id: "q19",
        prompt: "What does the `fallthrough` keyword do inside a `switch` case?",
        options: [
          { id: "a", text: "Nothing — it's not valid Swift syntax" },
          { id: "b", text: "It causes execution to continue into the next case's body, regardless of whether that next case's pattern matches" },
          { id: "c", text: "It exits the switch statement immediately" },
          { id: "d", text: "It's required at the end of every case for the switch to compile" },
        ],
        correctOptionId: "b",
        explanation: "`fallthrough` is Swift's explicit opt-in to C-style fall-through behavior — after `fallthrough`, execution moves directly into the very next case's body without evaluating whether that case's own pattern matches.",
      },
      {
        id: "q20",
        prompt: "Consider a `switch` over `(Any) ` values using `case let n as Int where n < 0:`. What does this pattern require to match?",
        options: [
          { id: "a", text: "The value must simply be non-nil" },
          { id: "b", text: "The value must successfully cast to `Int` (via `as`), AND the `where` condition (`n < 0`) must also be true" },
          { id: "c", text: "The value must be a `String` representation of a negative number" },
          { id: "d", text: "The `where` clause is ignored when combined with `as` casting" },
        ],
        correctOptionId: "b",
        explanation: "This combines a type-casting pattern (`as Int`) with a `where` clause — Swift first attempts to bind the value as an `Int`; only if that succeeds does it then evaluate the `where` condition. Both must hold for the case to be selected, which is a common pattern when switching over heterogeneous `Any` collections.",
      },
    ],
  },
  {
    id: "collections-quiz",
    title: "Collections Quiz",
    description: "20 questions on Array, Dictionary, Set, and the map/filter/reduce family.",
    relatedArticleSlug: "collections",
    questions: [
      {
        id: "q1",
        prompt: "What happens when you access an out-of-bounds index on an `Array`, e.g. `[1, 2, 3][5]`?",
        options: [
          { id: "a", text: "It returns `nil`" },
          { id: "b", text: "It returns the last valid element instead" },
          { id: "c", text: "It crashes at runtime with \"Index out of range\"" },
          { id: "d", text: "It's a compile-time error" },
        ],
        correctOptionId: "c",
        explanation: "Unlike dictionary subscripting, `Array` subscripting traps at runtime on an invalid index rather than returning an optional or clamping to a valid value. This is why safe access patterns (`indices.contains`, `.first`/`.last`, or a custom `[safe:]` extension) matter for untrusted indices.",
      },
      {
        id: "q2",
        prompt: "Why can't you call `.append(_:)` on an array declared with `let`?",
        options: [
          { id: "a", text: "`append` doesn't exist on `Array` — only `insert` does" },
          { id: "b", text: "Mutability is a property of the binding; a `let` array is immutable, so all mutating methods are disallowed" },
          { id: "c", text: "`append` only works on `Set`, not `Array`" },
          { id: "d", text: "It's allowed, but only for arrays of value types" },
        ],
        correctOptionId: "b",
        explanation: "As with all value types in Swift, whether a variable can be mutated depends on whether it's declared with `var` or `let`. A `let`-declared array cannot use `append`, `insert`, `remove`, `sort()`, or any other mutating member — you'd need to redeclare it with `var`.",
      },
      {
        id: "q3",
        prompt: "What is the benefit of a custom `subscript(safe:)` extension on `Array`, such as `numbers[safe: 5]`?",
        options: [
          { id: "a", text: "It makes the array sort automatically" },
          { id: "b", text: "It returns an optional (`nil` for an invalid index) instead of crashing, unlike the standard subscript" },
          { id: "c", text: "It changes the array's element type to `Any`" },
          { id: "d", text: "It's identical in behavior to the standard subscript, just slower" },
        ],
        correctOptionId: "b",
        explanation: "A safe-subscript extension checks `indices.contains(index)` internally and returns `Element?`, gracefully returning `nil` for an invalid index rather than trapping — useful when working with indices that aren't guaranteed to be valid.",
      },
      {
        id: "q4",
        prompt: "What does subscripting a `Dictionary` with a key that doesn't exist return, e.g. `ages[\"Dave\"]` when `\"Dave\"` isn't a key?",
        options: [
          { id: "a", text: "A runtime crash, just like an out-of-bounds array access" },
          { id: "b", text: "`nil`, because dictionary subscripting always returns an optional" },
          { id: "c", text: "`0` by default" },
          { id: "d", text: "A compile-time error" },
        ],
        correctOptionId: "b",
        explanation: "Dictionary subscripting always returns an optional (`Value?`) because a missing key is treated as a normal, expected outcome rather than a programmer error — a deliberate contrast to `Array`'s crash-on-invalid-index behavior.",
      },
      {
        id: "q5",
        prompt: "What does `visitCounts[\"profile\", default: 0]` do if `\"profile\"` isn't currently a key in `visitCounts`?",
        options: [
          { id: "a", text: "It crashes" },
          { id: "b", text: "It inserts `\"profile\": 0` into the dictionary permanently" },
          { id: "c", text: "It returns `0` as a fallback value without modifying the dictionary (unless you use it as the target of a compound assignment like `+=`)" },
          { id: "d", text: "It throws a runtime error requiring `try?`" },
        ],
        correctOptionId: "c",
        explanation: "The `default:` subscript parameter supplies a fallback value to read when the key is missing, avoiding manual `if let`/`??` boilerplate. It becomes especially useful in a compound assignment like `wordCounts[word, default: 0] += 1`, which both reads the fallback and writes the incremented value back.",
      },
      {
        id: "q6",
        prompt: "Why is `Set.contains(_:)` generally faster than `Array.contains(_:)` for membership testing on large collections?",
        options: [
          { id: "a", text: "`Set` stores its elements in sorted order, enabling binary search" },
          { id: "b", text: "`Set` membership testing is average O(1), backed by hashing, versus `Array`'s O(n) linear scan" },
          { id: "c", text: "There is no actual performance difference between them" },
          { id: "d", text: "`Array.contains` is deprecated in modern Swift" },
        ],
        correctOptionId: "b",
        explanation: "`Set` requires elements to conform to `Hashable` and uses that hash to locate elements directly, giving average O(1) membership checks. `Array.contains` must scan linearly through elements, which is O(n) — this difference becomes significant as collections grow.",
      },
      {
        id: "q7",
        prompt: "Given `let a: Set = [1, 2, 3, 4]` and `let b: Set = [3, 4, 5, 6]`, what does `a.subtracting(b)` return?",
        options: [
          { id: "a", text: "`{5, 6}`" },
          { id: "b", text: "`{3, 4}`" },
          { id: "c", text: "`{1, 2}`" },
          { id: "d", text: "`{1, 2, 3, 4, 5, 6}`" },
        ],
        correctOptionId: "c",
        explanation: "`subtracting` returns the elements present in `a` but not in `b`. Since `3` and `4` are shared, they're removed, leaving `{1, 2}`. (`a.intersection(b)` would give `{3, 4}`, and `a.union(b)` would give all six elements.)",
      },
      {
        id: "q8",
        prompt: "What is the difference between `sorted()` and `sort()` on an array?",
        options: [
          { id: "a", text: "They are identical in every way" },
          { id: "b", text: "`sorted()` returns a new sorted array without mutating the original; `sort()` mutates the array in place and returns nothing" },
          { id: "c", text: "`sort()` only works on arrays of `String`" },
          { id: "d", text: "`sorted()` requires a `var` array; `sort()` works on `let`" },
        ],
        correctOptionId: "b",
        explanation: "`sorted()`/`sorted(by:)` produce a new array, leaving the original untouched (and can be called on a `let` array). `sort()`/`sort(by:)` mutate the array directly, requiring a `var`-declared array, and don't return a value.",
      },
      {
        id: "q9",
        prompt: "What does `numbers.map { $0 * 2 }` produce, given `numbers = [1, 2, 3]`?",
        options: [
          { id: "a", text: "`[1, 2, 3]` unchanged" },
          { id: "b", text: "`[2, 4]` — one element dropped" },
          { id: "c", text: "`[2, 4, 6]` — the same element count, each transformed" },
          { id: "d", text: "A single value: `12`" },
        ],
        correctOptionId: "c",
        explanation: "`map` transforms every element 1:1 — the result always has the same number of elements as the input, just with each one passed through the closure. It never filters or drops elements; that's the job of `filter`.",
      },
      {
        id: "q10",
        prompt: "What does `numbers.filter { $0 % 2 == 0 }` do?",
        options: [
          { id: "a", text: "Transforms every element into a boolean" },
          { id: "b", text: "Returns a new array containing only the elements for which the closure returned `true`" },
          { id: "c", text: "Removes all elements and returns an empty array" },
          { id: "d", text: "Sorts the array by evenness" },
        ],
        correctOptionId: "b",
        explanation: "`filter` keeps only elements matching a predicate closure, discarding the rest, and returns a new collection — the original is untouched (for `Array`; the mutating in-place variant is `removeAll(where:)`, not `filter`).",
      },
      {
        id: "q11",
        prompt: "What does `numbers.reduce(0) { $0 + $1 }` compute, given `numbers = [1, 2, 3, 4, 5]`?",
        options: [
          { id: "a", text: "`[1, 2, 3, 4, 5]` unchanged" },
          { id: "b", text: "`120` (the product)" },
          { id: "c", text: "`15` (the sum, starting the accumulator at `0`)" },
          { id: "d", text: "`0`, since the initial value overrides everything" },
        ],
        correctOptionId: "c",
        explanation: "`reduce` combines every element into a single accumulated value, starting from the given initial value (`0` here) and applying the closure cumulatively: `0+1=1`, `1+2=3`, `3+3=6`, `6+4=10`, `10+5=15`.",
      },
      {
        id: "q12",
        prompt: "What is the key difference between `map` and `compactMap` when converting `[\"1\", \"2\", \"abc\"]` using `{ Int($0) }`?",
        options: [
          { id: "a", text: "They produce identical results" },
          { id: "b", text: "`map` produces `[Optional(1), Optional(2), nil]`; `compactMap` produces `[1, 2]`, automatically dropping the failed conversion" },
          { id: "c", text: "`compactMap` crashes on the invalid string `\"abc\"`" },
          { id: "d", text: "`map` automatically sorts the results; `compactMap` does not" },
        ],
        correctOptionId: "b",
        explanation: "`map` preserves every element's transformed result, including `nil`s, giving you an array of optionals. `compactMap` performs the same transformation but then automatically unwraps and discards any `nil` results, giving you a clean array of only the successful conversions.",
      },
      {
        id: "q13",
        prompt: "What does `flatMap` do differently from `map` when working with `[[1, 2, 3], [4, 5]]`?",
        options: [
          { id: "a", text: "They behave identically for nested arrays" },
          { id: "b", text: "`flatMap` maps each inner array through the closure and then flattens all the resulting sequences into one single-level array" },
          { id: "c", text: "`flatMap` only works on dictionaries" },
          { id: "d", text: "`flatMap` sorts the flattened result automatically" },
        ],
        correctOptionId: "b",
        explanation: "`flatMap` is designed for when each element maps to a *sequence* — it flattens those sequences into one combined result. `nested.flatMap { $0 }` on `[[1, 2, 3], [4, 5]]` gives `[1, 2, 3, 4, 5]`, whereas plain `map { $0 }` would just return the original nested array unchanged.",
      },
      {
        id: "q14",
        prompt: "Why is `numbers.first(where: { $0 % 2 == 0 })` generally more efficient than `numbers.filter { $0 % 2 == 0 }.first`?",
        options: [
          { id: "a", text: "They perform identically — this is a myth" },
          { id: "b", text: "`first(where:)` short-circuits and stops scanning as soon as a match is found, while `filter(...).first` must build the entire filtered array first" },
          { id: "c", text: "`filter` always throws an error on large arrays" },
          { id: "d", text: "`first(where:)` only works on sorted arrays" },
        ],
        correctOptionId: "b",
        explanation: "`first(where:)` stops as soon as it finds the first matching element. `filter` must fully process the entire source collection to build a complete filtered array before `.first` can even be taken from it — wasted work if you only needed the first match.",
      },
      {
        id: "q15",
        prompt: "What does `for (index, fruit) in fruits.enumerated()` provide inside the loop body?",
        options: [
          { id: "a", text: "Only the fruit values, with indices discarded" },
          { id: "b", text: "Each element paired with its integer offset within the collection" },
          { id: "c", text: "A random sampling of elements with a random index" },
          { id: "d", text: "The count of fruits, repeated for each iteration" },
        ],
        correctOptionId: "b",
        explanation: "`enumerated()` pairs every element with its zero-based integer offset, replacing manual index-tracking loops (`var i = 0; for fruit in fruits { ...; i += 1 }`) with a clean, direct tuple destructuring in the `for-in` loop.",
      },
      {
        id: "q16",
        prompt: "What happens with `zip(names, ages)` if `names` has 3 elements and `ages` has only 2?",
        options: [
          { id: "a", text: "It crashes with a runtime error" },
          { id: "b", text: "It pads the shorter sequence with `nil` values" },
          { id: "c", text: "It produces only 2 pairs, stopping at the length of the shorter sequence, silently dropping the extra element from the longer one" },
          { id: "d", text: "It throws a compile-time error requiring equal-length arrays" },
        ],
        correctOptionId: "c",
        explanation: "`zip` pairs elements positionally from two sequences and stops once the shorter sequence is exhausted — any extra elements in the longer sequence are simply never included in the output, with no error or crash.",
      },
      {
        id: "q17",
        prompt: "Given `let slice = numbers[1...3]` where `numbers = [10, 20, 30, 40, 50]`, what is true about `slice[1]`?",
        options: [
          { id: "a", text: "It returns `20`, the same as if the slice were zero-indexed" },
          { id: "b", text: "It crashes, because `ArraySlice` preserves the original array's indices rather than renumbering from zero — index `1` isn't within the slice's valid range (which starts at `1` and needs index `2` for the second element)" },
          { id: "c", text: "`ArraySlice` doesn't support subscripting at all" },
          { id: "d", text: "It returns the same result as `slice.first`" },
        ],
        correctOptionId: "b",
        explanation: "This is a well-known `ArraySlice` gotcha: slicing doesn't reindex from zero — it keeps the original array's index numbering. `slice[1]` is invalid because the slice's valid indices are `1...3` (matching the original array), so you'd need `slice[2]` to get the value `30`. Converting with `Array(slice)` gives you a proper zero-based array.",
      },
      {
        id: "q18",
        prompt: "What's the recommended practice for long chains of collection operations like `.filter { }.map { }.reduce(0, +)`?",
        options: [
          { id: "a", text: "Always cram them onto a single line, regardless of length, for consistency" },
          { id: "b", text: "Avoid chaining altogether and always use manual `for` loops instead" },
          { id: "c", text: "Two or three chained operations read fine inline; beyond that, put one operation per line (or use named intermediate variables) to keep the pipeline scannable" },
          { id: "d", text: "Chaining more than one operation is a compile error" },
        ],
        correctOptionId: "c",
        explanation: "Chaining is idiomatic Swift and works well for a couple of operations inline, but a long dense one-liner becomes hard to scan and debug. Breaking each stage onto its own line — one `.filter`, one `.map`, one `.reduce` per line — keeps each transformation step clear and easy to breakpoint individually.",
      },
      {
        id: "q19",
        prompt: "What is the main benefit of using `.lazy` before a chain like `numbers.lazy.map { ... }.filter { ... }.first`?",
        options: [
          { id: "a", text: "It automatically sorts the results" },
          { id: "b", text: "It guarantees thread safety" },
          { id: "c", text: "It defers computation so elements are only processed as needed, avoiding full intermediate arrays — valuable when you only need a small subset of results (like `.first`) from a large or expensive-to-transform source" },
          { id: "d", text: "It converts the array to a `Set` to remove duplicates" },
        ],
        correctOptionId: "c",
        explanation: "Without `.lazy`, each `map`/`filter` call eagerly processes the *entire* collection and builds a full intermediate array before the next step runs. `.lazy` defers all of that, computing only as many elements as are actually consumed — which can save significant work when you only need a few results (e.g., `.first` or `.prefix(3)`) from a very large source.",
      },
      {
        id: "q20",
        prompt: "What is a downside of using `.lazy` sequences compared to eager collection operations?",
        options: [
          { id: "a", text: "`.lazy` sequences cannot be iterated more than once, ever" },
          { id: "b", text: "A lazy sequence re-runs its transform closures every time you iterate it again, since results aren't cached — so it isn't ideal when you need to reuse the same computed results repeatedly" },
          { id: "c", text: "`.lazy` always produces incorrect results for `filter`" },
          { id: "d", text: "`.lazy` only works with `Dictionary`, not `Array`" },
        ],
        correctOptionId: "b",
        explanation: "Laziness trades away caching for deferred computation — every time you iterate a lazy sequence, its transformation closures run again from scratch. For a one-time consumption of a small prefix, this is a big win; if you need the same result set multiple times, converting back to a stored `Array(...)` once is usually better.",
      },
    ],
  },
  {
    id: "optionals-quiz",
    title: "Optionals Quiz",
    description: "20 questions on nil, unwrapping, optional chaining, nil-coalescing, and force unwrapping.",
    relatedArticleSlug: "optionals",
    questions: [
      {
        id: "q1",
        prompt: "Which of these can actually be assigned `nil`?",
        options: [
          { id: "a", text: "`var name: String = \"Nahidul\"`" },
          { id: "b", text: "`var middleName: String? = \"Ahmed\"`" },
          { id: "c", text: "Both A and B" },
          { id: "d", text: "Neither — `nil` doesn't exist in Swift" },
        ],
        correctOptionId: "b",
        explanation: "Only optional types (declared with a trailing `?`) can hold `nil`. A plain `String` can never be `nil` — assigning `nil` to it is a compile-time error, since the type system enforces the distinction entirely at compile time.",
      },
      {
        id: "q2",
        prompt: "What is `Optional` actually implemented as, under the hood?",
        options: [
          { id: "a", text: "A special compiler primitive with no user-visible type" },
          { id: "b", text: "A generic enum with two cases: `.none` and `.some(Wrapped)`" },
          { id: "c", text: "A subclass of `NSObject`" },
          { id: "d", text: "A protocol that any type can conform to" },
        ],
        correctOptionId: "b",
        explanation: "`Optional<Wrapped>` is a standard-library enum with cases `.none` (equivalent to `nil`) and `.some(Wrapped)` (holding an actual value). `let a: Int? = nil` and `let a: Int? = Optional.none` are exactly equivalent.",
      },
      {
        id: "q3",
        prompt: "Why does `let doubled = age * 2` fail to compile when `age` is declared as `Int?`?",
        options: [
          { id: "a", text: "`Int?` doesn't support multiplication at all, even after unwrapping" },
          { id: "b", text: "You cannot use an optional's value directly as its underlying type without first unwrapping it" },
          { id: "c", text: "`age` must be declared with `var`, not `let`, to be used in arithmetic" },
          { id: "d", text: "It's a runtime error, not a compile-time one" },
        ],
        correctOptionId: "b",
        explanation: "Swift requires you to unwrap an optional — via `if let`, `guard let`, force-unwrap, or similar — before treating it as its underlying, non-optional type. This is enforced by the compiler, precisely to prevent accidentally operating on a value that might not exist.",
      },
      {
        id: "q4",
        prompt: "What does the shorthand `if let username { ... }` do (introduced in Swift 5.7)?",
        options: [
          { id: "a", text: "It's invalid syntax — you must always write `if let username = username`" },
          { id: "b", text: "It unwraps `username` and shadows it with the same name, so inside the block `username` refers to the unwrapped, non-optional value" },
          { id: "c", text: "It only works for `Bool` optionals" },
          { id: "d", text: "It force-unwraps `username`, crashing if it's `nil`" },
        ],
        correctOptionId: "b",
        explanation: "The shorthand lets you avoid writing `if let username = username`, instead shadowing the existing optional with an unwrapped constant of the same name — a concise convenience for the extremely common case of unwrapping a variable into itself.",
      },
      {
        id: "q5",
        prompt: "What is the key structural difference between `guard let` and `if let` when unwrapping an optional?",
        options: [
          { id: "a", text: "There is no difference" },
          { id: "b", text: "`guard let`'s unwrapped binding remains available for the rest of the enclosing scope; `if let`'s binding is only available inside its own indented block" },
          { id: "c", text: "`guard let` can only be used inside classes" },
          { id: "d", text: "`if let` requires an explicit `else`, while `guard let` does not" },
        ],
        correctOptionId: "b",
        explanation: "This scope difference is why `guard let` is preferred for validating multiple inputs at the top of a function — it keeps the \"happy path\" flat instead of nesting deeper with every additional `if let` check, since each `guard let` binding stays in scope afterward.",
      },
      {
        id: "q6",
        prompt: "Given `struct Person { var address: Address? }` and `struct Address { var street: String }`, what does `person.address?.street` evaluate to if `person.address` is `nil`?",
        options: [
          { id: "a", text: "It crashes at runtime" },
          { id: "b", text: "It evaluates to `nil`, short-circuiting the rest of the chain without crashing" },
          { id: "c", text: "It returns an empty string `\"\"`" },
          { id: "d", text: "It's a compile-time error" },
        ],
        correctOptionId: "b",
        explanation: "Optional chaining (`?.`) propagates `nil` through the entire chain the moment any link is `nil` — there's no crash, and the whole expression simply evaluates to `nil` rather than attempting to access `.street` on a nonexistent `Address`.",
      },
      {
        id: "q7",
        prompt: "In `let displayName = username ?? \"Guest\"`, when is `\"Guest\"` actually used?",
        options: [
          { id: "a", text: "Always, regardless of `username`'s value" },
          { id: "b", text: "Only when `username` is `nil`" },
          { id: "c", text: "Only when `username` is an empty string" },
          { id: "d", text: "Never — `??` only works with numeric types" },
        ],
        correctOptionId: "b",
        explanation: "The nil-coalescing operator `??` evaluates to the left-hand value if it's non-nil, and falls back to the right-hand default only when the left side is `nil`. The right-hand side is evaluated lazily (short-circuited) — it's skipped entirely if the left side already has a value.",
      },
      {
        id: "q8",
        prompt: "What happens when you force-unwrap (`!`) an optional that is actually `nil`?",
        options: [
          { id: "a", text: "It silently returns a default value like `0` or `\"\"`" },
          { id: "b", text: "It's a compile-time error, caught before running" },
          { id: "c", text: "It's an immediate runtime crash (\"Unexpectedly found nil while unwrapping an Optional value\")" },
          { id: "d", text: "It returns `nil` again, unchanged" },
        ],
        correctOptionId: "c",
        explanation: "Force-unwrapping asserts to the compiler that the optional definitely holds a value. If that assertion is wrong, the app crashes immediately with a fatal error — there's no recoverable exception to catch, which is why `!` should be reserved for cases with a genuine structural guarantee.",
      },
      {
        id: "q9",
        prompt: "What is the primary legitimate modern use case for declaring a new implicitly unwrapped optional (`String!`) in your own code?",
        options: [
          { id: "a", text: "They're the default recommended way to declare all optional properties" },
          { id: "b", text: "There is essentially no reason to write a new one in modern Swift — they exist mainly for Objective-C interop and legacy patterns like `@IBOutlet`, and you should recognize them in existing code rather than write new ones" },
          { id: "c", text: "They avoid the performance cost of regular optionals" },
          { id: "d", text: "They're required for all `class` properties" },
        ],
        correctOptionId: "b",
        explanation: "Implicitly unwrapped optionals exist almost entirely for interoperability with older Objective-C APIs and specific UIKit patterns like `@IBOutlet` (nil until the view loads, then guaranteed set). In new Swift code, prefer a regular optional (`?`) and unwrap it safely, or restructure so the value is genuinely non-optional from the start.",
      },
      {
        id: "q10",
        prompt: "In `switch response { case 200?: ...; case nil: ... }` where `response` is `Int?`, what does the `200?` pattern match?",
        options: [
          { id: "a", text: "Any value greater than 200" },
          { id: "b", text: "Specifically the case where `response` holds the value `200` (equivalent to `.some(200)`)" },
          { id: "c", text: "It's invalid syntax" },
          { id: "d", text: "It matches only `nil`" },
        ],
        correctOptionId: "b",
        explanation: "The `value?` shorthand in a switch pattern is equivalent to writing `.some(value)` explicitly — it matches only when the optional holds that specific wrapped value. `case nil:` (equivalent to `.none`) separately handles the absent case.",
      },
      {
        id: "q11",
        prompt: "Given `let age: Int? = 25`, what does `age.map { $0 * 2 }` produce?",
        options: [
          { id: "a", text: "`50` directly, as a plain `Int`" },
          { id: "b", text: "`Optional(50)` — the transformation is applied to the wrapped value, and the result is re-wrapped in an optional" },
          { id: "c", text: "`nil`, because `map` doesn't work on optionals" },
          { id: "d", text: "A runtime crash" },
        ],
        correctOptionId: "b",
        explanation: "`Optional` supports `map` just like collections do — it applies the closure to the wrapped value if one exists, and produces a new optional wrapping the result. If the original optional were `nil`, the closure would never run and the result would simply be `nil`.",
      },
      {
        id: "q12",
        prompt: "Why would `numberString.map { Int($0) }` be problematic if `numberString` is a `String?`, compared to using `flatMap` instead?",
        options: [
          { id: "a", text: "`map` isn't defined for `String?` at all" },
          { id: "b", text: "`map`'s closure itself returns an optional (`Int?`, since `Int(String)` is failable), so the result becomes a nested optional `Int??`; `flatMap` flattens this back down to a single `Int?`" },
          { id: "c", text: "`flatMap` is simply a deprecated alias for `map`" },
          { id: "d", text: "There's no actual difference between the two here" },
        ],
        correctOptionId: "b",
        explanation: "The rule is: use `map` when your closure returns a plain value, and `flatMap` when your closure itself returns an optional. Since `Int(someString)` already returns `Int?`, wrapping that result again via `map` produces `Int??`; `flatMap` avoids that extra nesting level.",
      },
      {
        id: "q13",
        prompt: "What does a nested optional like `Int??` typically indicate?",
        options: [
          { id: "a", text: "A compiler bug" },
          { id: "b", text: "That the value has been double-wrapped — often from a dictionary of optional values (`[String: Int?]`) or from using `map` where `flatMap` was actually needed" },
          { id: "c", text: "That the value is guaranteed non-nil" },
          { id: "d", text: "A special Swift type used only for JSON parsing" },
        ],
        correctOptionId: "b",
        explanation: "Nested optionals most commonly arise from subscripting a dictionary whose *values* are themselves optional, or from a `map` call whose closure returns an optional (which should have used `flatMap` instead, as in Q12). They can be collapsed with `flatMap { $0 }` or by unwrapping twice.",
      },
      {
        id: "q14",
        prompt: "For `let dict: [String: Int?] = [\"score\": nil]`, what does `dict[\"score\"]` actually evaluate to?",
        options: [
          { id: "a", text: "A plain `nil`" },
          { id: "b", text: "`Optional(nil)` — the outer optional (from the subscript) is `.some`, because the key exists, while it wraps an inner `.none` (the stored value itself is nil)" },
          { id: "c", text: "It throws a runtime error" },
          { id: "d", text: "`0`" },
        ],
        correctOptionId: "b",
        explanation: "This is the classic nested-optional distinction: the key `\"score\"` genuinely exists in the dictionary (so the subscript's outer optional is non-nil), but the *value* stored for that key is itself `nil`. This differs meaningfully from looking up a key that doesn't exist at all, where the subscript's outer optional would be plain `nil`.",
      },
      {
        id: "q15",
        prompt: "Do two optionals of a `Comparable` type support direct `==` comparison, e.g. `let a: Int? = 5; let b: Int? = nil; a == b`?",
        options: [
          { id: "a", text: "No, `==` is never defined for optional types" },
          { id: "b", text: "Yes — optionals of `Equatable`/`Comparable` types support `==` directly, comparing wrapped values, and treating `nil == nil` as `true`" },
          { id: "c", text: "Only if both sides are explicitly force-unwrapped first" },
          { id: "d", text: "It always returns `true` regardless of the actual values" },
        ],
        correctOptionId: "b",
        explanation: "`==` works out of the box on optionals: two non-nil optionals compare their wrapped values, two `nil` optionals are considered equal to each other, and a `nil` compared to a non-nil value is `false`. In the example given, `a == b` evaluates to `false` (5 vs. nil).",
      },
      {
        id: "q16",
        prompt: "Why does `[Int?].sorted()` fail to compile directly, without a custom comparator?",
        options: [
          { id: "a", text: "Arrays of optionals cannot be sorted under any circumstances" },
          { id: "b", text: "Optionals are not `Comparable` by default, since there's no universally correct rule for whether `nil` should sort before or after real values — Swift refuses to guess" },
          { id: "c", text: "`sorted()` only works on `String` arrays" },
          { id: "d", text: "It's a runtime error, not a compile-time one" },
        ],
        correctOptionId: "b",
        explanation: "While `==` is defined for optionals, ordering operators (`<`, `>`) are not, because there's no single correct answer for where `nil` belongs in a sort order. You must supply `sorted(by:)` with custom logic (or substitute a sentinel default via `??`) to explicitly decide.",
      },
      {
        id: "q17",
        prompt: "What does `scores.sorted { ($0 ?? Int.max) < ($1 ?? Int.max) }` accomplish for an array of `Int?`?",
        options: [
          { id: "a", text: "It crashes on any `nil` element" },
          { id: "b", text: "It sorts real values normally, while pushing all `nil` elements to the end of the result (by treating them as `Int.max` for comparison purposes only)" },
          { id: "c", text: "It removes all `nil` elements from the array" },
          { id: "d", text: "It sorts `nil` values before all real values" },
        ],
        correctOptionId: "b",
        explanation: "Substituting `Int.max` for `nil` (via `??`) only for the purposes of the comparison closure means every real value will compare as \"less than\" any `nil`, effectively pushing all `nil`s to the end of the sorted result, without altering the original array's actual contents.",
      },
      {
        id: "q18",
        prompt: "Which unwrapping approach is most appropriate for validating three optional function parameters at the top of a function, each with a different failure message?",
        options: [
          { id: "a", text: "Nesting three separate `if let` blocks, one inside another" },
          { id: "b", text: "Three separate `guard let ... else { return ... }` statements in sequence" },
          { id: "c", text: "Force-unwrapping all three with `!`" },
          { id: "d", text: "A single `switch` statement with sixteen combined cases" },
        ],
        correctOptionId: "b",
        explanation: "Sequential `guard let` statements let each precondition fail independently with its own specific error/return message, while keeping all successfully-unwrapped bindings available afterward without nesting — this is the standard idiomatic pattern for validating multiple inputs.",
      },
      {
        id: "q19",
        prompt: "In `if let first, let last { print(\"\\(first) \\(last)\") }`, what happens if `last` is `nil` but `first` has a value?",
        options: [
          { id: "a", text: "The block still runs, printing `first` with an empty string for `last`" },
          { id: "b", text: "It crashes" },
          { id: "c", text: "The entire condition fails, and the block does not execute at all — every comma-separated binding must succeed" },
          { id: "d", text: "It falls back to a default value for `last`" },
        ],
        correctOptionId: "c",
        explanation: "When multiple optional bindings are chained with commas in a single `if let`, all of them must successfully unwrap for the block to execute. If any one of them is `nil`, the whole condition fails and control moves to the `else` branch (if present) or simply skips the block.",
      },
      {
        id: "q20",
        prompt: "What does `user.profileImageURLString.flatMap { URL(string: $0) }` produce as its overall type, given `profileImageURLString` is `String?` and `URL(string:)` is a failable initializer returning `URL?`?",
        options: [
          { id: "a", text: "`URL??`, a doubly-nested optional" },
          { id: "b", text: "`URL?` — a single-level optional, because `flatMap` flattens the optional-returning closure's result instead of nesting it" },
          { id: "c", text: "`URL`, non-optional, since `flatMap` always unwraps completely" },
          { id: "d", text: "A compile-time error, since `flatMap` doesn't accept failable initializers" },
        ],
        correctOptionId: "b",
        explanation: "This is exactly the use case `flatMap` is for: the closure itself returns an optional (`URL?`), so using `flatMap` instead of `map` avoids producing a nested `URL??` and instead yields a clean, single-level `URL?`.",
      },
    ],
  },
  {
    id: "functions-and-closures-quiz",
    title: "Functions and Closures Quiz",
    description: "20 questions on parameters, closures, capturing, escaping, and higher-order functions.",
    relatedArticleSlug: "functions-and-closures",
    questions: [
      {
        id: "q1",
        prompt: "What is true about `func square(_ n: Int) -> Int { n * n }`?",
        options: [
          { id: "a", text: "It requires an explicit `return` keyword or it fails to compile" },
          { id: "b", text: "It uses implicit return, valid for single-expression function bodies since Swift 5.1" },
          { id: "c", text: "It's invalid Swift syntax — functions must always specify `-> Void` if returning nothing" },
          { id: "d", text: "`n * n` is treated as a discarded statement, and the function actually returns nothing" },
        ],
        correctOptionId: "b",
        explanation: "Since Swift 5.1, a function (or closure) whose body is a single expression can omit the `return` keyword entirely — the expression's value is returned implicitly. A function returning nothing can similarly omit `-> Void`, since it's the implicit default.",
      },
      {
        id: "q2",
        prompt: "In `func move(from start: Int, to end: Int)`, what are `from`/`to` versus `start`/`end`?",
        options: [
          { id: "a", text: "They're identical and interchangeable — Swift doesn't distinguish between them" },
          { id: "b", text: "`from`/`to` are external argument labels used at the call site; `start`/`end` are internal parameter names used inside the function body" },
          { id: "c", text: "`start`/`end` are used at the call site; `from`/`to` are used inside the body" },
          { id: "d", text: "`from`/`to` are optional and can be omitted entirely at the call site" },
        ],
        correctOptionId: "b",
        explanation: "Swift functions have two names per parameter: an external label (what callers write, e.g. `move(from: 0, to: 10)`) and an internal name (what the function body uses internally, e.g. `start`, `end`). This dual-naming lets APIs read naturally at the call site while using clear short names internally.",
      },
      {
        id: "q3",
        prompt: "What does writing `_` as a parameter's external label accomplish, e.g. `func square(_ number: Int) -> Int`?",
        options: [
          { id: "a", text: "It makes the parameter optional" },
          { id: "b", text: "It suppresses the external label entirely, so callers write `square(5)` instead of `square(number: 5)`" },
          { id: "c", text: "It hides the parameter from autocomplete only" },
          { id: "d", text: "It makes the parameter variadic" },
        ],
        correctOptionId: "b",
        explanation: "`_` before a parameter name removes the requirement for an external label at the call site — useful when the label would be redundant, as with `square(5)` where writing `square(number: 5)` would add no clarity.",
      },
      {
        id: "q4",
        prompt: "Given `func greet(name: String, greeting: String = \"Hello\") -> String`, what happens if you call `greet(name: \"Nahidul\")`?",
        options: [
          { id: "a", text: "It's a compile-time error — all parameters must be supplied" },
          { id: "b", text: "It compiles fine, using `\"Hello\"` automatically for `greeting` since it has a default value" },
          { id: "c", text: "It compiles but crashes at runtime because `greeting` is unset" },
          { id: "d", text: "`greeting` becomes `nil`" },
        ],
        correctOptionId: "b",
        explanation: "Parameters with a default value can be omitted entirely by the caller — Swift substitutes the default automatically. Defaults can even reference other parameters or call other functions to compute a value.",
      },
      {
        id: "q5",
        prompt: "In `func sum(_ numbers: Int...) -> Int`, what type is `numbers` exposed as inside the function body?",
        options: [
          { id: "a", text: "A single `Int`" },
          { id: "b", text: "`[Int]`, a plain array" },
          { id: "c", text: "`Int?`" },
          { id: "d", text: "A tuple of unknown length" },
        ],
        correctOptionId: "b",
        explanation: "A variadic parameter (marked with `...`) accepts zero or more values of the same type at the call site, and is exposed inside the function body as a regular array of that type — here, `[Int]`. A function can have at most one variadic parameter.",
      },
      {
        id: "q6",
        prompt: "Why must you write `increment(&counter)` with an explicit `&` when calling `func increment(_ value: inout Int)`?",
        options: [
          { id: "a", text: "It's purely decorative and has no actual meaning" },
          { id: "b", text: "It makes the potential mutation visible right at the call site, and is required syntax for passing an argument by reference to an `inout` parameter" },
          { id: "c", text: "It converts `counter` to an optional" },
          { id: "d", text: "It's only required when `counter` is a global variable" },
        ],
        correctOptionId: "b",
        explanation: "`inout` parameters are passed by reference rather than by value, meaning changes inside the function propagate back to the caller's variable. The explicit `&` is a deliberate design choice — it makes potential mutation visible at the call site, unlike languages where reference semantics are invisible.",
      },
      {
        id: "q7",
        prompt: "Can you pass a `let` constant as an argument to an `inout` parameter?",
        options: [
          { id: "a", text: "Yes, always" },
          { id: "b", text: "No — `inout` requires a mutable variable (`var`); passing a `let` constant is a compile-time error" },
          { id: "c", text: "Only if the constant is of type `Int`" },
          { id: "d", text: "Yes, but only inside closures" },
        ],
        correctOptionId: "b",
        explanation: "Since `inout` allows the function to mutate the caller's variable, the argument must be something that can actually be mutated — a `var`. Passing a `let` constant produces the compile-time error \"cannot pass immutable value as inout argument.\"",
      },
      {
        id: "q8",
        prompt: "What is the benefit of returning a named tuple like `(min: Int, max: Int)` from a function, over an unnamed one like `(Int, Int)`?",
        options: [
          { id: "a", text: "There's no difference — names are purely cosmetic and invisible even in code" },
          { id: "b", text: "Named tuple elements make the call site self-documenting, letting you write `result.min`/`result.max` instead of the less clear `result.0`/`result.1`" },
          { id: "c", text: "Named tuples perform better at runtime" },
          { id: "d", text: "Only named tuples can be returned from a function; unnamed tuples cannot" },
        ],
        correctOptionId: "b",
        explanation: "Named tuple elements are a lightweight, zero-cost way to make a multi-value return type self-explanatory — `bounds.min` is far clearer to a reader than `bounds.0`, though both work identically under the hood.",
      },
      {
        id: "q9",
        prompt: "What does the `@discardableResult` attribute do?",
        options: [
          { id: "a", text: "It causes the function to always return `Void`" },
          { id: "b", text: "It silences the compiler's default warning about an unused non-`Void` return value, for functions where ignoring the result is a legitimate, common choice" },
          { id: "c", text: "It removes the return value entirely at compile time" },
          { id: "d", text: "It forces callers to always use the return value" },
        ],
        correctOptionId: "b",
        explanation: "By default, Swift warns when you call a function and ignore its non-`Void` return value. `@discardableResult` opts a function out of that specific warning — for example, `removeLast()` returns the removed element, but you often don't need to capture it.",
      },
      {
        id: "q10",
        prompt: "What is true about a nested function, e.g. a `subtotal()` function defined inside `processOrder(...)`?",
        options: [
          { id: "a", text: "It's visible and callable from anywhere in the file, just like a top-level function" },
          { id: "b", text: "It's only visible within its enclosing function, and it automatically captures variables from the enclosing scope, just like a closure" },
          { id: "c", text: "It cannot access any variables from the enclosing function" },
          { id: "d", text: "Nested functions are not allowed in Swift" },
        ],
        correctOptionId: "b",
        explanation: "Nested functions are scoped entirely to their enclosing function — invisible outside it — and they capture the enclosing function's variables automatically, behaving essentially like named closures. This is exactly how the `makeCounter()` pattern (returning a nested function that keeps incrementing a captured `count`) works.",
      },
      {
        id: "q11",
        prompt: "Which of these closure expressions is equivalent to `numbers.sorted(by: { (a: Int, b: Int) -> Bool in return a < b })`?",
        options: [
          { id: "a", text: "`numbers.sorted(by: { $0 < $1 })` only" },
          { id: "b", text: "`numbers.sorted(by: <)` only" },
          { id: "c", text: "Both `numbers.sorted(by: { $0 < $1 })` and `numbers.sorted(by: <)` are equivalent, along with several other progressively shortened forms" },
          { id: "d", text: "None of the shortened forms are actually equivalent — they behave differently" },
        ],
        correctOptionId: "c",
        explanation: "Swift lets you progressively drop redundant syntax from a closure — explicit types, the `return` keyword for single-expression bodies, and even the parameter list itself (using `$0`/`$1` shorthand, or passing an operator function like `<` directly) — all while producing identical behavior.",
      },
      {
        id: "q12",
        prompt: "What does trailing closure syntax allow you to do, e.g. `numbers.sorted { $0 < $1 }` instead of `numbers.sorted(by: { $0 < $1 })`?",
        options: [
          { id: "a", text: "It changes the closure's behavior to run asynchronously" },
          { id: "b", text: "It moves a function's final (or only) closure argument outside the parentheses, dropping its label — the idiomatic, common way closures appear in real Swift code" },
          { id: "c", text: "It's only valid for closures with zero parameters" },
          { id: "d", text: "It requires the closure to return `Void`" },
        ],
        correctOptionId: "b",
        explanation: "When a closure is a function's last (or sole) argument, Swift allows it to be written outside the call's parentheses, with the label dropped. If it's the only argument, the parentheses themselves can be omitted entirely, as in `numbers.sorted { $0 < $1 }`.",
      },
      {
        id: "q13",
        prompt: "How does Swift handle a function that needs **multiple** trailing closures, such as `fetchData { ... } onFailure: { ... }`?",
        options: [
          { id: "a", text: "This has never been supported in Swift" },
          { id: "b", text: "Since Swift 5.3, additional trailing closures after the first are each labeled at the closure boundary" },
          { id: "c", text: "Only the first trailing closure can ever have a label" },
          { id: "d", text: "Multiple trailing closures must all be unlabeled" },
        ],
        correctOptionId: "b",
        explanation: "Swift 5.3 introduced support for multiple trailing closures: the first one can be unlabeled (matching the parameter it's assigned to), and each subsequent trailing closure is written with its own label directly before its braces, e.g. `onFailure: { error in ... }`.",
      },
      {
        id: "q14",
        prompt: "In `numbers.map { $0 * 2 }`, what does `$0` refer to?",
        options: [
          { id: "a", text: "The index of the current element" },
          { id: "b", text: "The first parameter of the closure — here, each element being mapped" },
          { id: "c", text: "A global counter variable" },
          { id: "d", text: "The entire array being mapped over" },
        ],
        correctOptionId: "b",
        explanation: "`$0`, `$1`, `$2`, etc. are shorthand names referring to a closure's parameters positionally, letting you skip declaring named parameters for short, self-evident closures. `$0` is the first (and, in a single-parameter closure like this one, only) parameter.",
      },
      {
        id: "q15",
        prompt: "What does it mean that a closure \"captures\" a variable from its surrounding scope, as in `makeMultiplier(factor:)` returning a closure that uses `factor`?",
        options: [
          { id: "a", text: "The closure receives a frozen, one-time copy of the variable's value at creation time, always" },
          { id: "b", text: "By default, the closure keeps a live reference to the captured variable/constant, not a frozen snapshot — later mutations to a captured `var` are visible inside the closure" },
          { id: "c", text: "Captured variables are always converted to global variables" },
          { id: "d", text: "Closures cannot reference any variables outside their own parameter list" },
        ],
        correctOptionId: "b",
        explanation: "Captures are references by default, not copies — this is exactly why two closures sharing a captured `var total` (as in the `makeIncrementers()` example) can both observe and affect the same underlying value across multiple calls, not independent copies of it.",
      },
      {
        id: "q16",
        prompt: "What problem does `[weak self]` in a closure's capture list solve?",
        options: [
          { id: "a", text: "It makes the closure run on a background thread" },
          { id: "b", text: "It breaks a strong reference cycle that could otherwise occur when a class stores a closure that itself strongly captures `self`, keeping the object alive indefinitely" },
          { id: "c", text: "It converts `self` into a value type" },
          { id: "d", text: "It's required syntax for every closure, regardless of context" },
        ],
        correctOptionId: "b",
        explanation: "By default, closures capture reference types like `self` strongly, keeping them alive for the closure's lifetime. If a class stores such a closure as a property (e.g. `onComplete`), and that closure captures `self`, you get a retain cycle — neither object can ever be deallocated. `[weak self]` captures `self` as an optional, weak reference instead, breaking the cycle.",
      },
      {
        id: "q17",
        prompt: "Why must a closure parameter that's going to be stored and called later (e.g. as a network completion handler) be marked `@escaping`?",
        options: [
          { id: "a", text: "`@escaping` makes the closure run faster" },
          { id: "b", text: "By default, closures are non-escaping, meaning the compiler guarantees they'll be called (or discarded) before the function returns; `@escaping` explicitly allows the closure to be stored and potentially called after the function has already returned" },
          { id: "c", text: "`@escaping` is required for every closure parameter, with no exceptions" },
          { id: "d", text: "It converts the closure into a nested function" },
        ],
        correctOptionId: "b",
        explanation: "Non-escaping closures (the default) are guaranteed by the compiler not to outlive the function call they were passed into, enabling certain optimizations. `@escaping` is required whenever a closure might be stored in a property or called asynchronously after the function returns — like a completion handler saved for a later network callback.",
      },
      {
        id: "q18",
        prompt: "What is the purpose of `@autoclosure`, as used implicitly by the standard library's `??` operator?",
        options: [
          { id: "a", text: "It forces immediate evaluation of the expression before the function call happens" },
          { id: "b", text: "It automatically wraps a plain expression argument into a closure, deferring its evaluation, without requiring the caller to write explicit `{ }` braces" },
          { id: "c", text: "It converts the expression's result into an optional" },
          { id: "d", text: "It's identical in effect to `@escaping`" },
        ],
        correctOptionId: "b",
        explanation: "`@autoclosure` lets a function parameter accept a plain expression at the call site while treating it internally as a closure — deferring evaluation until (and unless) it's actually needed. This is exactly why the right-hand side of `??` is only evaluated when the left side is `nil`, without the caller needing to write `expensiveDefault` as `{ expensiveDefault() }`.",
      },
      {
        id: "q19",
        prompt: "What does it mean that \"closures are values\" in Swift, e.g. `let operation: (Int, Int) -> Int = add`?",
        options: [
          { id: "a", text: "It's not actually valid syntax — functions cannot be assigned to variables" },
          { id: "b", text: "Named functions are just closures with a name attached, so they (and closures generally) can be assigned to constants, passed as arguments, stored in arrays, and returned from other functions, just like an `Int` or `String`" },
          { id: "c", text: "Only closures created with `{ }` syntax can be treated this way; named functions cannot" },
          { id: "d", text: "This only works for functions with zero parameters" },
        ],
        correctOptionId: "b",
        explanation: "Functions and closures are first-class values in Swift — a named function's identifier (without call parentheses) refers to the function itself, which can be stored, passed around, and invoked later, exactly like any other value of a matching function type.",
      },
      {
        id: "q20",
        prompt: "What defines a \"higher-order function\"?",
        options: [
          { id: "a", text: "Any function marked `@escaping`" },
          { id: "b", text: "A function that either takes another function/closure as a parameter, or returns one — like the standard library's `map`, or a custom `repeatAction(times:action:)`" },
          { id: "c", text: "Only functions belonging to a class hierarchy" },
          { id: "d", text: "A function that must return a tuple" },
        ],
        correctOptionId: "b",
        explanation: "Higher-order functions operate on other functions, either by accepting them as parameters (like `repeatAction(times:action:)` calling its `action` closure repeatedly) or by returning them (like `makeValidator(minimumLength:)` returning a configured validator closure). `map`, `filter`, and `reduce` are all higher-order functions from the standard library, but you can write your own with exactly the same shape.",
      },
    ],
  },
];

export function getAllQuizzes(): Quiz[] {
  return quizzes;
}

export function getQuiz(id: string): Quiz | undefined {
  return quizzes.find((quiz) => quiz.id === id);
}
